### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by Soulbadguy54** [iann838/pulsefire#8]
Hello, not a single method works ... Help plz

code:
```
import asyncio
from pulsefire.clients import RiotAPIClient

DEFAULT_REGION = 'euw1'


async def main():

    async with RiotAPIClient(default_headers={"X-Riot-Token": "Here my token"}) as lol_client:
        matches = await lol_client.get_account_v1_by_puuid(region=DEFAULT_REGION, puuid="32lQUu9Awz9kvu1IAkeiLxRtVbtBYfvVWQIOHgzNAZnc3QFshayziwsjfu4U0FRiajWPaMLLWOck5w")
        print(matches)
        
asyncio.run(main())
```

Got this traceback independent on method invoked:
```
Traceback (most recent call last):
  File "G:\python projects\TusaDaunovV2\tests\lol_api.py", line 39, in <module>
    asyncio.run(main())
  File "C:\Users\Soulbadguy\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Soulbadguy\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Soulbadguy\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "G:\python projects\TusaDaunovV2\tests\lol_api.py", line 12, in main
    matches = await lol_client.get_account_v1_by_puuid(region=DEFAULT_REGION, puuid="32lQUu9Awz9kvu1IAkeiLxRtVbtBYfvVWQIOHgzNAZnc3QFshayziwsjfu4U0FRiajWPaMLLWOck5w")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\python projects\TusaDaunovV2\.venv\Lib\site-packages\pulsefire\clients.py", line 380, in get_account_v1_by_puuid
    return await self.invoke("GET", "/riot/account/v1/accounts/by-puuid/{puuid}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\python projects\TusaDaunovV2\.venv\Lib\site-packages\pulsefire\clients.py", line 147, in invoke
    return await self.middleware_begin(invocation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\python projects\TusaDaunovV2\.venv\Lib\site-packages\pulsefire\middlewares.py", line 97, in middleware
    response: aiohttp.ClientResponse = await next(invocation)
                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\python projects\TusaDaunovV2\.venv\Lib\site-packages\pulsefire\middlewares.py", line 68, in middleware
    response.raise_for_status()
  File "G:\python projects\TusaDaunovV2\.venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://euw1.api.riotgames.com/riot/account/v1/accounts/by-puuid/32lQUu9Awz9kvu1IAkeiLxRtVbtBYfvVWQIOHgzNAZnc3QFshayziwsjfu4U0FRiajWPaMLLWOck5w')
```

**Comment by Soulbadguy54** [comment]
Whats about get_matches via user puuid? Is it the same problem? When i should use euw1? Only in get match by id?

**Comment by iann838** [comment]
@Soulbadguy54 Please refer to the developer portal on which are the correct regions to request them
https://developer.riotgames.com/apis#match-v5/GET_getMatch
![image](https://github.com/iann838/pulsefire/assets/58193352/e94dcbb9-5f9b-4df1-aebf-3ae450e565a6)
